POST http://localhost:8080/auth/registration
Content-Type: application/json
#Authorization: Bearer

{
  "name": "Bahrom",
  "surname": "Bahromov",
  "email": "bahrom@gmail.com",
  "phone": "998990109090",
  "password": "1265"
}


###

POST http://localhost:8080/auth/login
Content-Type: application/json


{
  "email": "malikovbehzod2001@gmail.com",
  "password": "444"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json


{
  "email": "rrr@wwww",
  "password": "2885"
}

###

POST http://localhost:8080/auth/verification
Content-Type: application/json

{
  "phone": "998990109090",
  "code": 36743
}

###

GET http://localhost:8080/auth/resend/998988199891
Content-Type: application/json

###

GET http://localhost:8080/auth/resend/998914640003
Content-Type: application/json