POST http://localhost:8080/profile/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NTg5NjYsImV4cCI6MTY3MDk3NDk2NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.KEvi09q8IcRX7aZ2IAvwIWAWwU78DpeBZjAU5rcPhIs

{
  "name": "Sardor",
  "surname": "Sardorov",
  "email": "sa7999@@9988ik",
  "password": "2225",
  "role": "ROLE_USER",
  "phone": "998914640909",
  "attachId": "de1cb0e4-3753-4b6c-81c0-3f79bcedf5c2"
}

###

PUT http://localhost:8080/profile/adm/updateByAdmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NTg5NjYsImV4cCI6MTY3MDk3NDk2NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.KEvi09q8IcRX7aZ2IAvwIWAWwU78DpeBZjAU5rcPhIs

{
  "id" : 22,
  "name": "Shamshot",
  "surname": "Shamshotov",
  "password": "28895",
  "phone": "99891499999"
}

###

PUT http://localhost:8080/profile/current/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NTg5NjYsImV4cCI6MTY3MDk3NDk2NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.KEvi09q8IcRX7aZ2IAvwIWAWwU78DpeBZjAU5rcPhIs

{
 "attachId": "fd7b3e8d-4518-41fc-aa64-2a8dae1cca52"
}

###

PUT http://localhost:8080/profile/user/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NzA5MjksImV4cCI6MTY3MDk4NjkyOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxOSwicm9sZSI6IlJPTEVfVVNFUiJ9.mv9oMBLA03penGlwhq1fGBVV2k8paDgvqzOkTx3ASq4

{
  "id" : 19,
  "name": "Sherzod",
  "surname": "Shermatov",
  "password": "2885",
  "phone": "99891499999"
}


###

GET localhost:8080/profile/adm/list?page=1&size=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NTg5NjYsImV4cCI6MTY3MDk3NDk2NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.KEvi09q8IcRX7aZ2IAvwIWAWwU78DpeBZjAU5rcPhIs

 {
   "role": "all"
 }

###

DELETE http://localhost:8080/profile/adm/delete/24
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NTg5NjYsImV4cCI6MTY3MDk3NDk2NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.KEvi09q8IcRX7aZ2IAvwIWAWwU78DpeBZjAU5rcPhIs

###

POST localhost:8080/profile/adm/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzA3NTg5NjYsImV4cCI6MTY3MDk3NDk2NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.KEvi09q8IcRX7aZ2IAvwIWAWwU78DpeBZjAU5rcPhIs

{
  "name": "Sardor"
}