
POST http://localhost:8080/types/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU4NDA1NjEsImV4cCI6MTY1NjA1NjU2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hc-Zvy9Wi3V7b5HGp0IFqg_GYt_h3JPVG8B43hqLdq4

{
  "key": "sport",
  "nameUz": "uz",
  "nameRu": "ru",
  "nameEn": "en"
}

###

GET http://localhost:8080/types/adm/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU4NDA1NjEsImV4cCI6MTY1NjA1NjU2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hc-Zvy9Wi3V7b5HGp0IFqg_GYt_h3JPVG8B43hqLdq4

###

PUT http://localhost:8080/types/adm/update/olam
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU4NDA1NjEsImV4cCI6MTY1NjA1NjU2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hc-Zvy9Wi3V7b5HGp0IFqg_GYt_h3JPVG8B43hqLdq4

{
  "key": "olaam"
}

###
DELETE localhost:8080/types/adm/delete/olaam
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyMTM1MTMsImV4cCI6MTY1NTIxNzExMywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.g4UibfGApMButTppoyRUIDMYl4YXdrFXeHnuUkK0rH8
